### ISSUE TITLE
Using SomeWrapperType inside another type

### ISSUE THREAD

**Issue by davidwalschots** [joaofbantunes/GetComplexTypeFromQueryAsSimpleType#1]
Hi João. Thanks for your [blog post](https://dev.to/joaofbantunes/getting-a-complex-type-as-a-simple-type-from-the-query-string-in-a-aspnet-core-api-controller-oa2) on getting a complex type from a simple type from the query string. Like you I also spent a lot of time figuring out how getting rid of the primitive obsession is possible within ASP.NET. It's definitely a quirky subject and I found your blog post to be very helpful.

I'm wondering if you ever figured out how to handle cases where the complex type is part of another type? For example, having the following controller method and `Input` type, as forked [here](https://github.com/davidwalschots/GetComplexTypeFromQueryAsSimpleType).

```csharp
[HttpPost("basic")]
public IActionResult GetWithNoCustomization(Input wrapper) => Ok(wrapper.Prop.Value);
```

```csharp
public class Input
{
    public SomeWrapperType Prop { get; set; }
}
```

Sadly this results in a HTTP 400 with the following response:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-4ddb1281a666d712f4c747c1dc3d99cd-fe761e86961aed62-00",
  "errors": {
    "wrapper": [
      "The wrapper field is required."
    ],
    "$.prop": [
      "The JSON value could not be converted to Api.SomeWrapperType. Path: $.prop | LineNumber: 1 | BytePositionInLine: 15."
    ]
  }
}
```

**Comment by joaofbantunes** [comment]
Hey! Glad the post was useful.

What's your objective with this? To have a single complex object (`Input`, in this case) that gets it properties from other places?

**Comment by joaofbantunes** [comment]
Just as I side note: even though what I wrote in the post still applies, I changed a bit my way of thinking, and lately try to avoid these kinds of things, keeping it a bit simpler, receiving the simple types and doing the transformation at the API code level, before passing it on to the domain code.

Messing with model binding, JSON converters and other similar stuff is nice for quick and easy stuff, but can get overly complex if you try to do too much magic and abstraction.

**Comment by davidwalschots** [comment]
I'd like a POST request body such as:

```json
{
  "prop": "123"
}
```

To convert to a complex object (pseudo code):
```
Input {
    Prop = SomeWrapperType {
        Value = 123
    }
}
```
Potentially the `Input` type may contain other properties of other types (custom or not, having `TypeConverter`/`TryParse` or not.

Internally I'm assuming .NET uses the `ComplexObjectModelBinder` in a situation like this. What's interesting is that the `ComplexObjectModelBinder` will without fail bind e.g. a `DateTime` which is part of the complex object (likely using the `DateTimeModelBinder` internally, though I don't know for sure), yet it fails to understand that `SomeWrapperType` should be bound using the `SimpleObjectModelBinder`.

> Messing with model binding, JSON converters and other similar stuff is nice for quick and easy stuff, but can get overly complex if you try to do too much magic and abstraction.

Given all the complexities involved in getting this to work, I'm definitely starting to agree with you on this 😀.

**Comment by joaofbantunes** [comment]
Got it. Yeah, I tried to do something similar in the past and didn't get it to work.
Not sure if it's possible now, at least not easily. I mean, I'm pretty sure it's doable, if you want to implement a custom JSON converter or something similar, with a bunch of magic. Now if this is the best route to go about, I'm not so sure 😅

**Comment by davidwalschots** [comment]
Yeah. Thus far I came to the same conclusion. Which really is a shame. If I ever figure out a way to do it easily I'll let you know.

**Comment by davidwalschots** [comment]
Whenever `[FromBody]` is applied (or inferred by ASP.NET which is what happens when you post JSON), the whole model binder doesn't execute. This is also documented [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-8.0#frombody-attribute):

> Apply the `[FromBody]` attribute to a parameter to populate its properties from the body of an HTTP request. The ASP.NET Core runtime delegates the responsibility of reading the body to an input formatter.

Thus the input formatter mechanism is necessary to get this to work. `System.Text.Json` does not support `TypeConverter`. This is intentional as I discovered [here](https://github.com/dotnet/runtime/issues/38812#issuecomment-948929862). A useful implementation to map between `TypeConverter` and `JsonConverter` can be found [here](https://github.com/dotnet/runtime/issues/1761#issuecomment-723647307). One would register this as follows:

```csharp
builder.Services
    .AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters.Add(new TypeConverterJsonAdapter());
    });
```

The difference in requirements for type conversion between minimal APIs and `ApiController` APIs is also funky and doesn't make things better. It basically means having to implement both a type converter and a `TryParse` method if you want to support both and want to make it work in all situations. Implementing `IParsable<TSelf>` is recommended (this was called `IParseable<TSelf>` before .NET 7).

Indeed. All this is a bit of an underwhelming experience.

**Comment by davidwalschots** [comment]
@joaofbantunes I noted down some thoughts on the subject in [this post](https://davidwalschots.github.io/2024/01/05/model-binding-away-from-primitive-obsession-in-aspnet-web-apis) and made sure to link to your blog post on the subject as well.
